### ISSUE TITLE
How to Video Guides on MetaMask Wallet

### ISSUE THREAD

**Issue by EtherWorldCo** [Avarch-org/EtherWorld#10]
- [x] How to Add MetaMask to Chrome Browser? 
- [x] How to Export Private Key & Secret Recovery Phrase from MetaMask Wallet?
- [x] How to Check Available Test Networks in MetaMask Wallet?
- [x] How to Check Ethereum Address of MetaMask Account?
- [x] How to Install Metamask and Import an Ethereum Account to MetaMask?
- [x] How to Rename and Create a New Account on Existing MetaMask wallet?
- [x] How to Import Existing Ethereum Wallet to MetaMask Wallet?
- [x] How to Use Polygon testnet?
- [x] How to Use BSC Testnet?

**Comment by yashkamalchaturvedi** [comment]
How to Add MetaMask to Chrome Browser? - https://youtu.be/HBURVTzlZYM
 How to Export Private Key & Secret Recovery Phrase from MetaMask Wallet? - https://youtu.be/L7qenuFmGLk
 How to Check Available Test Networks in MetaMask Wallet? - https://youtu.be/L7qenuFmGLk
 How to Check Ethereum Address of MetaMask Account? - https://youtu.be/fZVFvHgs9vU
 How to Install Metamask and Import an Ethereum Account to MetaMask? - https://youtu.be/gu8ggJsI7v4
 How to Rename and Create a New Account on Existing MetaMask wallet? - https://youtu.be/SCEViBLxqrw
 How to Import Existing Ethereum Wallet to MetaMask Wallet? - https://youtu.be/66qL7HCiTV0
 How to Use Polygon testnet? - https://youtu.be/_rc5b2RGV7M
 How to Use BSC Testnet? - https://youtu.be/MZJEFPopBMc

**Comment by yashkamalchaturvedi** [comment]
Done
