### ISSUE TITLE
Ethereum Shadow forking

### ISSUE THREAD

**Issue by EtherWorldCo** [Avarch-org/EtherWorld#11]
A blogpost on Ethereum Shadow forking

@yashkamalchaturvedi 
- [x] What is Shadow forking
- [x] Goreli Shadow fork
- [x] Mainnet shadow fork

@Vishal-Vemon 
- [x] Cover image
- [x] Insta image

**Comment by yashkamalchaturvedi** [comment]
Blog - https://etherworld.co/2022/04/20/ethereum-mainnet-shadow-forking-an-overview/
