### ISSUE TITLE
First Post Merge Upgrade {Fork Next Upgrade}

### ISSUE THREAD

**Issue by EtherWorldCo** [Avarch-org/EtherWorld#12]
Blog by @yashkamalchaturvedi 

Points to Be Covered:
- [x] Explain: What is it?
- [x] What is EIP-2124?
- [x] Why is this upgrade needed?
- [x] Why not included in The Merge upgrade?
- [x] Sepolia Testnet Upgrade
- [x] When: Future Plans for Goerli, Mainnet

Assets by @Vishal-Vemon 

Points to Be Covered:
- [x] Cover Image
- [x] Sepolia Timeline
- [x] Fork Hash

**Comment by yashkamalchaturvedi** [comment]
https://etherworld.co/2022/10/07/ethereum-post-merge-hardfork-for-execution-layer/
