### ISSUE TITLE
The Evolution of Ethereum Testnets

### ISSUE THREAD

**Issue by EtherWorldCo** [Avarch-org/EtherWorld#18]
- [x] What is an Ethereum Testnet?
- [x] Difference between Mainnet, Testnet, Devnet
- [x] Popular Ethereum Test Networks
- [x] Proof of Work (PoW) Testnet
  - Olympic Testnet
  - Morden Testnet
  - Ropsten Testnet
  - Sepolia Testnet
- [x] Client Integration Testnets
  - YOLO
  - Aleut
  - Baikal
  - Calaveras
- [x] PoA Testnet
  - Kovan Testnet
  - Rinkeby Testnet
  - Goerli Testnet
- [x] PoS Testnet
- [x] Single Client Testnets
- [x] Prysm
  - Sapphire Testnet
  - Topaz Testnet
  - Onyx Testnet
- [x] Teku
  - Coorparoo Testnet
- [x] Multi-Client Testnets
  - Schlesi Testnet
  - Witti Testnet
  - Altona Testnet
  - Medalla Testnet
  - Spadina Testnet
  - Zinken Testnet
  - Toledo Testnet
- [x] Public Attacknets
  - Single-client beta-0 attacknets
  - Multi-client beta-1 attacknets
- [x] Pyrmont Testnet
- [x] Prater Testnet
- [x] Merge Testnets
  - Rayonism Testnet
  - Nocturne Testnet
  - Devnets 0-5
  - Amphora Testnet
  - Pithos Testnet
  - Kintsugi Testnet
  - Kiln Testnet
- [x] Shadow Forking
  - Goerli Shadow Fork
  - Mainnet Shadow Fork
- [x] Transition of Public Testnet Merge
  - Ropsten - RBC
  - Sepolia - SBC
  - Goerli- Prater
- [x] Others Testnets - Ganache CLI & GUI
- [x] Why use testnets?

**Comment by yashkamalchaturvedi** [comment]
https://etherworld.co/2022/08/19/the-evolution-of-ethereum-testnet/
