### ISSUE TITLE
Ethereum - Merge Kiln test

### ISSUE THREAD

**Issue by EtherWorldCo** [Avarch-org/EtherWorld#5]
- [x] Document an introductory blog post on Kiln testnet
- [x] Create a video to explain 
  - How is Kiln different from Kintsugi?
  - How to Connect to Kiln with Metamask?
  - How to Get Funds from the Faucet? 
  - How to Do a Transaction on Kiln Testnet?
- [x] Short Video on What is Kiln Testnet?

**Comment by EtherWorldCo** [comment]
- A blog post on Kiln testnet - https://etherworld.co/2022/03/14/how-to-join-ethereum-merge-kiln-testnet/
- How is Kiln different from Kintsugi? https://www.youtube.com/watch?v=4x6zJddzdyc&list=PLZmWIkdMcWY6FupNSjf9sRrq9WjG6eryR&index=3

**Comment by yashkamalchaturvedi** [comment]
- What is Kiln Testnet? - https://youtu.be/l7ArfYI38EQ

**Comment by yashkamalchaturvedi** [comment]
Done
