### ISSUE TITLE
YouTube Channel trailer 

### ISSUE THREAD

**Issue by EtherWorldCo** [Avarch-org/EtherWorld#7]
Create a YouTube channel trailer for people to engage subscription.

**Comment by yashkamalchaturvedi** [comment]
@Vishal-Vemon

**Comment by yashkamalchaturvedi** [comment]
https://youtu.be/BVbiVI40weA  by @Vishal-Vemon 
https://twitter.com/ether_world/status/1571170597245431810 by @yashkamalchaturvedi
