### ISSUE TITLE
MEV Research Report

### ISSUE THREAD

**Issue by EtherWorldCo** [Avarch-org/EtherWorld#8]
Document a research report on MEV
- [x] A detailed study of MEV 
- [x] Conduct a research on what reports available
- [x] Document key points to create a report summarizing your findings
  - Abstract
  - History
  - What is MEV?
  - How miners can earn profit from MEV? Write about different techniques.
  - List popular MEV types
  - Effects on DeFi to different user groups?
  - Available solutions to deal with MEV?
  - Novel means and best practices in application design for minimizing MEV (Miner Extractable Value) in DeFi applications. 
  - What should developers be thinking about? 
  - What are some of the easier changes that can be made to reduce MEV? 
  - What are some of the longer term solutions that will require further R&D?
  - Frequently Asked Questions
  - Conclusion
  - Resources
- [x] Create a cover image for the blog post
- [x] Create flow diagram for different types of MEV or general representation of how MEV works
- [x] Create Instagram image for the post

**Comment by EtherWorldCo** [comment]
- [ ] Front Runner, Back Runner MEV, Sandwich Attack, NFT MEV,

**Comment by yashkamalchaturvedi** [comment]
https://etherworld.co/2022/04/05/mev-research-report/

**Comment by yashkamalchaturvedi** [comment]
Done
