### ISSUE TITLE
A short video on Ethereum renaming

### ISSUE THREAD

**Issue by EtherWorldCo** [Avarch-org/EtherWorld#9]
## _**The Great Renaming in Ethereum Blockchain**_

**Resources** for reference
- https://notes.ethereum.org/@timbeiko/great-renaming
- https://blog.ethereum.org/2022/01/24/the-great-eth2-renaming/

Create a short video
- [x] Record the audio
- [x] Convert it into a video with help of doodle or animation
- [x] Create an attractive thumbnail
  - Add images/text Eth1, Eth2, Ether logo, curious question etc 
- [x] Share the link of the live video
- [x] Share on different social media
- [x] Create an Instagram post

**Comment by yashkamalchaturvedi** [comment]
https://youtu.be/nJ57mkttCH0
